let links_easter_eggs = new Map([
    ["01", "https://drive.google.com/file/d/1Mk3JtHy_2BmQUmxAO0jUkaWSpwHZs9T-/"],
    ["02", "https://drive.google.com/file/d/1F8V0a2SylEvPQ4f5WVfW1ai1EO8yxrYd/"],
    ["03", "https://drive.google.com/file/d/1WLAqmql2iKlntZgULH3VILq_8b3_Zjm2/"],
    ["04", "https://drive.google.com/file/d/1UgU9-1Zq5agGTBWaEJllOFH9nq1xJVPV/"],
    ["05", "https://drive.google.com/file/d/1-51U3qWMrfue_kc6wlDQYaX4-TtgdwNW/"],
    ["06", "https://drive.google.com/file/d/1rZwvS0icTYMLfFgoOm3j2D4syKoxYksJ/"],
    ["07", "https://drive.google.com/file/d/1g6j5mcP0PBmKi-JCVOrcJ1NLZivNyXkP/"],
    ["08", "https://drive.google.com/file/d/1ywcbZB_NvzMqTOQbysRCvVXZYRfHJf8H/"],
    ["09", "https://drive.google.com/file/d/1dhMjXQjnX1cLn33bWlriz4xzd6s_uA1l/"],
    ["10", "https://drive.google.com/file/d/12zi_9BgML0wE_QRv0seb8WCtwNVm-iLJ/"],
    ["11", "https://drive.google.com/file/d/1BD2wM8orBxN4ot0AeThdngVtG9Mey6gP/"],
    ["12", "https://drive.google.com/file/d/1-fWFO5SxjCXK-Jn8B-GDez1q5tppIKe1/"],
    ["13", "https://drive.google.com/file/d/1UzsuvTwEvVDlkIkgMRHdf1o5scYKfEwK/"],
    ["14", "https://drive.google.com/file/d/16Bi31OKUKZ5SJx6_2PQYA98ZkBtfQlR-/"],
    ["15", "https://drive.google.com/file/d/1bfx49Pnf2uAlUxhj5yg8lQEnzE4SrTjL/"],
    ["16", "https://drive.google.com/file/d/1H9UELZxiMDkPzGzICf4H90vqAst2arJU/"],
    ["17", "https://drive.google.com/file/d/1XT2Ktx2Ux6isI0e5olIuCup_7kdIr-HO/"],
    ["18", "https://drive.google.com/file/d/117Z_H6vd5GKhNL_TnowhvEeQ7XFfaoqf/"],
    ["19", "https://drive.google.com/file/d/1w3hsdy6U1-5pWqh0XSMEtgEk_XcAtBTs/"],
    ["20", "https://drive.google.com/file/d/1I0Zr3WTQg2JFDztQ4cdjKG-uV1yGh9YC/"],
    ["21", "https://drive.google.com/file/d/1Zv2lpDPBdfmGoE1_FpQEmMkijMcg9sHv/"]
]);